//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdfCreateService
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PageOrientation", Namespace="http://schemas.datacontract.org/2004/07/ProfileImages.Pdf")]
    internal enum PageOrientation : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Portrait = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Landscape = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PdfCreateService.IPdfCreateService")]
    internal interface IPdfCreateService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPdfCreateService/GetPdfFromUrl", ReplyAction="http://tempuri.org/IPdfCreateService/GetPdfFromUrlResponse")]
        byte[] GetPdfFromUrl(string url, PdfCreateService.PageOrientation orientation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPdfCreateService/GetPdfFromUrl", ReplyAction="http://tempuri.org/IPdfCreateService/GetPdfFromUrlResponse")]
        System.Threading.Tasks.Task<byte[]> GetPdfFromUrlAsync(string url, PdfCreateService.PageOrientation orientation);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    internal interface IPdfCreateServiceChannel : PdfCreateService.IPdfCreateService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    internal partial class PdfCreateServiceClient : System.ServiceModel.ClientBase<PdfCreateService.IPdfCreateService>, PdfCreateService.IPdfCreateService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PdfCreateServiceClient() : 
                base(PdfCreateServiceClient.GetDefaultBinding(), PdfCreateServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IPdfCreateService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PdfCreateServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(PdfCreateServiceClient.GetBindingForEndpoint(endpointConfiguration), PdfCreateServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PdfCreateServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PdfCreateServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PdfCreateServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PdfCreateServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PdfCreateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public byte[] GetPdfFromUrl(string url, PdfCreateService.PageOrientation orientation)
        {
            return base.Channel.GetPdfFromUrl(url, orientation);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetPdfFromUrlAsync(string url, PdfCreateService.PageOrientation orientation)
        {
            return base.Channel.GetPdfFromUrlAsync(url, orientation);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPdfCreateService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPdfCreateService))
            {
                return new System.ServiceModel.EndpointAddress("https://webservices-ext.uc.edu/NightRide/PdfCreate.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PdfCreateServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IPdfCreateService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PdfCreateServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IPdfCreateService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IPdfCreateService,
        }
    }
}
